"""Training Plan Model

Represents a structured multi-week training program with scheduled sessions.
Supports AI-generated plans with activity-aware recommendations.
"""
from datetime import date
from sqlalchemy import Column, String, Integer, Date, ForeignKey, Index, JSON
from sqlalchemy.orm import relationship
from app.models.base import Base, TimestampMixin
import uuid


class TrainingPlan(Base, TimestampMixin):
    """
    Training Plan Model
    
    Stores personalized training plans generated by the AI coach.
    Plans are linked to athlete goals and contain weekly structures with sessions.
    
    Attributes:
        id: Unique identifier (UUID)
        user_id: Reference to athlete (for user-scoped queries)
        title: Plan title (e.g., "Marathon Training")
        sport: Primary sport (running, cycling, swimming)
        goal_id: Reference to linked athlete goal
        start_date: Plan start date
        end_date: Plan end date
        status: Current status (draft, active, completed, abandoned)
        created_at: Timestamp when plan was created
        updated_at: Timestamp when plan was last updated
    """
    
    __tablename__ = 'training_plans'
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(Integer, ForeignKey('athletes.id', ondelete='CASCADE'), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    sport = Column(String(50), nullable=False)
    # primary = sport-specific training (one active per sport at a time)
    # complementary = nutrition, strength, recovery (can coexist with primary)
    plan_type = Column(String(20), nullable=False, default='primary')
    goal_id = Column(String(36), ForeignKey('athlete_goals.id', ondelete='SET NULL'), nullable=True)
    route_profile_id = Column(Integer, ForeignKey('route_profiles.id', ondelete='SET NULL'), nullable=True)
    plan_metadata = Column(JSON, nullable=True)  # performance_target, plan_rationale from LLM
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    status = Column(String(20), nullable=False, default='draft')
    
    # Relationships
    weeks = relationship('TrainingPlanWeek', back_populates='plan', cascade='all, delete-orphan', order_by='TrainingPlanWeek.week_number')
    goal = relationship('AthleteGoal', backref='training_plans')
    athlete = relationship('Athlete', backref='training_plans')
    
    # Indexes
    __table_args__ = (
        Index('idx_training_plans_user_id', 'user_id'),
        Index('idx_training_plans_status', 'status'),
    )
    
    def __repr__(self):
        return f"<TrainingPlan(id={self.id}, title={self.title}, sport={self.sport}, status={self.status})>"
    
    def validate(self):
        """Validate training plan data integrity."""
        errors = []
        
        # Validate status
        valid_statuses = ['draft', 'active', 'completed', 'abandoned']
        if self.status not in valid_statuses:
            errors.append(f"Invalid status: {self.status}. Must be one of {valid_statuses}")
        
        # Validate dates
        if self.start_date and self.end_date and self.start_date >= self.end_date:
            errors.append("start_date must be before end_date")
        
        # Validate sport
        valid_sports = ['running', 'cycling', 'swimming', 'triathlon', 'other']
        if self.sport and self.sport not in valid_sports:
            errors.append(f"Invalid sport: {self.sport}. Must be one of {valid_sports}")
        
        # Validate title
        if not self.title or len(self.title.strip()) == 0:
            errors.append("title cannot be empty")
        
        if errors:
            raise ValueError("; ".join(errors))
        
        return True
    
    def to_dict(self):
        """Convert plan to dictionary for API responses."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'title': self.title,
            'sport': self.sport,
            'goal_id': self.goal_id,
            'start_date': self.start_date.isoformat() if self.start_date else None,
            'end_date': self.end_date.isoformat() if self.end_date else None,
            'status': self.status,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }
